export const LOAD_PLAYLIST_REQUEST = 'LOAD_PLAYLIST_REQUEST'; 
export const LOAD_PLAYLIST_REQUEST_SUCCESS = 'LOAD_PLAYLIST_REQUEST_SUCCESS'; 
export const LOAD_PLAYLIST_REQUEST_FAILED = 'LOAD_PLAYLIST_REQUEST_FAILED'; 

export const PLAYER_STATUS_PLAYING = 'PLAYER_STATUS_PLAYING'; 
export const PLAYER_STATUS_PAUSED = 'PLAYER_STATUS_PAUSED'; 

export const SET_SONG_INFO = 'SET_SONG_INFO'; 